name: SFTP

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Deploy
              uses: wlixcc/SFTP-Deploy-Action@v1.2.4
              with:
                  server: ${{ secrets.SERVER }}
                  port: ${{ secrets.FTP_PORT }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  remote_path: "/"
                  sftp_only: true

            - name: Restart
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: sudo docker restart ${{ secrets.CONTAINER }}
